# This file was generated by GoReleaser. DO NOT EDIT.
class Xoauth < Formula
  desc "xoath is a cross-platform tool for obtaining JWTs from OpenId Connect providers"
  homepage "https://github.com/XeroAPI/xoauth"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/XeroAPI/xoauth/releases/download/v1.0.0/xoauth_1.0.0_darwin_amd64.tar.gz"
    sha256 "a5d4eba806d2af108774e167baa0da3104e9fd3baee35623fa59f9fe931835d2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/XeroAPI/xoauth/releases/download/v1.0.0/xoauth_1.0.0_linux_amd64.tar.gz"
      sha256 "46eb35fe747b7830d04f12cb16722376ff473fd18adc70f62a1f36ed89815913"
    end
  end

  def install
    bin.install "xoauth"
  end
end
